import { authTables } from "@convex-dev/auth/server";
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  ...authTables,
  // Convex Auth's users table plus the app's own fields. `createdAt` is
  // optional because auth-created users rely on _creationTime instead.
  users: defineTable({
    name: v.optional(v.string()),
    email: v.optional(v.string()),
    image: v.optional(v.string()),
    emailVerificationTime: v.optional(v.number()),
    phone: v.optional(v.string()),
    phoneVerificationTime: v.optional(v.number()),
    isAnonymous: v.optional(v.boolean()),
    createdAt: v.optional(v.number()),
  }).index("email", ["email"]),
  apiKeys: defineTable({
    userId: v.id("users"),
    provider: v.string(),
    encryptedKey: v.string(),
    last4: v.string(),
    validatedAt: v.number(),
  }).index("by_user_provider", ["userId", "provider"]),
  assetUploads: defineTable({
    userId: v.id("users"),
    storageId: v.id("_storage"),
    kind: v.union(v.literal("player"), v.literal("background"), v.literal("music")),
    contentType: v.string(),
    sizeBytes: v.number(),
    source: v.optional(v.union(v.literal("upload"), v.literal("generated"))),
    generationPrompt: v.optional(v.string()),
    status: v.union(v.literal("pending"), v.literal("approved"), v.literal("rejected")),
    reviewNote: v.optional(v.string()),
    reviewedAt: v.optional(v.number()),
    createdAt: v.number(),
  }).index("by_user", ["userId"]).index("by_status", ["status"]).index("by_storage", ["storageId"]),
  assetPacks: defineTable({
    userId: v.id("users"),
    artDirection: v.string(),
    playerUploadId: v.id("assetUploads"),
    backgroundUploadId: v.id("assetUploads"),
    musicUploadId: v.optional(v.id("assetUploads")),
    playerWidth: v.number(),
    playerHeight: v.number(),
    backgroundWidth: v.number(),
    backgroundHeight: v.number(),
    musicVolume: v.number(),
    createdAt: v.number(),
  }).index("by_user", ["userId"]),
  userSettings: defineTable({
    userId: v.id("users"),
    defaultProvider: v.union(v.literal("openai"), v.literal("anthropic"), v.literal("gemini")),
    modelTiers: v.object({
      openai: v.union(v.literal("fast"), v.literal("strong")),
      anthropic: v.union(v.literal("fast"), v.literal("strong")),
      gemini: v.union(v.literal("fast"), v.literal("strong")),
    }),
    updatedAt: v.number(),
  }).index("by_user", ["userId"]),
  games: defineTable({
    userId: v.id("users"),
    title: v.string(),
    genre: v.string(),
    isPublic: v.boolean(),
    plays: v.optional(v.number()),
    currentVersionId: v.optional(v.id("gameVersions")),
    createdAt: v.number(),
  }).index("by_user", ["userId"]).index("by_public", ["isPublic"]),
  gameVersions: defineTable({
    gameId: v.id("games"),
    version: v.number(),
    spec: v.any(),
    expectations: v.any(),
    parentVersionId: v.optional(v.id("gameVersions")),
    createdBy: v.union(v.literal("generate"), v.literal("refine"), v.literal("revert")),
    generation: v.optional(v.any()),
    verifyResult: v.any(),
    createdAt: v.number(),
  }).index("by_game", ["gameId", "version"]),
  generationJobs: defineTable({
    gameId: v.optional(v.id("games")),
    versionId: v.optional(v.id("gameVersions")),
    userId: v.id("users"),
    provider: v.union(v.literal("openai"), v.literal("anthropic"), v.literal("gemini")),
    modelTier: v.union(v.literal("fast"), v.literal("strong")),
    status: v.union(
      v.literal("queued"),
      v.literal("running"),
      v.literal("retrying"),
      v.literal("succeeded"),
      v.literal("failed"),
      v.literal("canceled"),
    ),
    stage: v.union(
      v.literal("queued"),
      v.literal("generating"),
      v.literal("persisting"),
      v.literal("verifying"),
      v.literal("completed"),
      v.literal("failed"),
      v.literal("canceled"),
    ),
    checkpoint: v.union(v.literal("none"), v.literal("generated"), v.literal("persisted"), v.literal("verified")),
    progress: v.number(),
    progressLog: v.array(v.string()),
    intent: v.any(),
    answers: v.any(),
    verifyLoops: v.array(v.any()),
    generatedSpec: v.optional(v.any()),
    expectations: v.optional(v.any()),
    generation: v.optional(v.any()),
    estimatedCostUsd: v.number(),
    attempt: v.number(),
    maxAttempts: v.number(),
    scheduledFunctionId: v.optional(v.id("_scheduled_functions")),
    nextAttemptAt: v.optional(v.number()),
    error: v.optional(v.string()),
    errorCode: v.optional(v.string()),
    startedAt: v.optional(v.number()),
    finishedAt: v.optional(v.number()),
    canceledAt: v.optional(v.number()),
    updatedAt: v.number(),
    createdAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_user_created", ["userId", "createdAt"])
    .index("by_provider_created", ["provider", "createdAt"])
    .index("by_status", ["status"]),
  generationJobEvents: defineTable({
    jobId: v.id("generationJobs"),
    userId: v.id("users"),
    stage: v.string(),
    level: v.union(v.literal("info"), v.literal("warning"), v.literal("error")),
    message: v.string(),
    attempt: v.number(),
    details: v.optional(v.any()),
    createdAt: v.number(),
  })
    .index("by_job", ["jobId", "createdAt"])
    .index("by_user", ["userId", "createdAt"]),
  publishes: defineTable({
    gameId: v.id("games"),
    versionId: v.id("gameVersions"),
    vercelProjectId: v.string(),
    url: v.string(),
    status: v.string(),
    createdAt: v.number(),
  }).index("by_game", ["gameId"]),
});
